name: birthday
description: A birthday reminder app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  built_collection: ^4.3.2
  built_value: ^7.0.8
  convert: ^2.1.1
  flutter_redux: ^0.6.0
  redux: ^4.0.0
  redux_logging: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  built_value_generator: ^7.0.8

flutter:
  uses-material-design: true